-- AlterTable
ALTER TABLE "Profile" ADD COLUMN     "dob" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "experience" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "income" INTEGER NOT NULL DEFAULT 10000,
ADD COLUMN     "milestones" JSONB,
ADD COLUMN     "percentIncomeInvested" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
ADD COLUMN     "riskToleranceQ1" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "riskToleranceQ2" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "riskToleranceQ3" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "riskToleranceQ4" INTEGER NOT NULL DEFAULT 3;
