

interface MarketUpdateProps {
    content: string | null
}

export default function MarketUpdate({ content }: MarketUpdateProps) {

    return (
        <div className='flex flex-col gap-3'>
            <span className=''>What&apos;s going on in the market?</span>

            {content && content.length > 0 ? (
            <>
                <div className='whitespace-pre-wrap text-sm'>
                    {content}
                </div>
                <div className='text-xs text-center'>
                    This summary was generated by AI. Please double-check important information and contact a financial adviser if you require advice.
                </div>
            </>
            ) : (
            <div className='flex items-center justify-center p-12'>
                <span>Something went wrong</span>
            </div>
            )}
        </div>
    )
}